apiVersion: apps/v1
kind: Deployment
metadata:
  name: lb324-deployment # Name des Deployments
spec:
  replicas: 3 # Anzahl der Pods, die erstellt werden sollen
  selector:
    matchLabels:
      app: lb324 # Label zum Finden der richtigen Pods
  template:
    metadata:
      labels:
        app: lb324 # Dieses Label wird den Pods zugewiesen
    spec:
      containers:
      - name: lb324-container # Name des Containers
        image: lb324:latest # Docker-Image, das du zuvor erstellt und hochgeladen hast
        ports:
        - containerPort: 80 # Port, auf dem der Container lauscht
