apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: lb324-service-monitor
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: lb324  # Match your service label here
  endpoints:
  - port: http  # Port name of the service
    path: /metrics  # Path for Prometheus to scrape
    interval: 15s

