apiVersion: v1
kind: Service
metadata:
  name: lb324-service
  namespace: monitoring
  labels:
    app: lb324
spec:
  ports:
    - port: 80
      targetPort: 5000  # Port of the application
      name: http
  selector:
    app: lb324  # Match your app's pod label

